### ISSUE TITLE
can't launch the application because of Tesserwrap

### ISSUE THREAD

**Issue by vojtapolasek** [chrys87/ocrdesktop#6]
Hello,
on latest ARch Linux, probably after upgrade to Python 3.10, the ap does not work.
I get this:
###
Traceback (most recent call last):
  File "/usr/bin/ocrdesktop", line 23, in <module>
    from tesserwrap import tesseract
  File "/usr/lib/python3.10/site-packages/tesserwrap/__init__.py", line 1, in <module>
    from .core import tr
  File "/usr/lib/python3.10/site-packages/tesserwrap/core.py", line 74, in <module>
    tr = load_library('libtesserwrap', os.path.dirname(__file__))
  File "/usr/lib/python3.10/site-packages/tesserwrap/core.py", line 70, in load_library
    raise exc
  File "/usr/lib/python3.10/site-packages/tesserwrap/core.py", line 67, in load_library
    return cdll[libpath]
  File "/usr/lib/python3.10/ctypes/__init__.py", line 449, in __getitem__
    return getattr(self, name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 444, in __getattr__
    dll = self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3.10/site-packages/libtesserwrap.so: cannot open shared object file: No such file or directory
###
However, the python-tesserwrap package is installed, I compiled it against the latest Python.

**Comment by chrys87** [comment]
as we use pytesseract now, this should be fixed
